# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# Requires https://github.com/apps/settings to be configured for the organization
# The documentation for these settings are in the settings repository and generally map onto the github rest api

# By being in the .github repository these apply globally to the whole organization
# These settings only apply at repository creation, the individual repositories can create/override their own rules

repository:
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  # only allow regular merge and squashes
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: false
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

#labels:
  # unused for now

#milestones:
  # unused for now

#collaborators:
  # unused for now

#teams:
  # unused for now

#branches:
  # unused for now
  # requires that the branches already exist
  # one required reviewer

rulesets:
  # one required reviewer
  - name: main
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "refs/heads/main"
        exclude: []
    rules:
      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: false
          require_last_push_approval: true
          required_approving_review_count: 1
          required_review_thread_resolution: false
      - type: non_fast_forward
      - type: deletion
  # no required reviewers
  - name: UAT
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "refs/heads/UAT"
        exclude: []
    rules:
      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: false
          require_last_push_approval: true
          required_approving_review_count: 0
          required_review_thread_resolution: false
      - type: non_fast_forward
      - type: deletion
  # no required reviewers, requires linear history to force squash merging
  - name: E2E
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "refs/heads/E2E"
        exclude: []
    rules:
      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: false
          require_last_push_approval: true
          required_approving_review_count: 0
          required_review_thread_resolution: false
      - type: non_fast_forward
      - type: deletion
      - type: required_linear_history
